### ISSUE TITLE
[Bug] Grader is reusing output as input when printing failed test cases

### ISSUE THREAD

**Issue by hyfi06** [PlatziMaster/challenge-python-09#11]
**Edit (by @pablotrinidad):** Failed test cases will have the same values in input and ouput data since this specific problem modifies input in place. Grader must create a shallow copy of the input array before sending it to the valuation function.

**Original:**
When a test case fails, in the terminal it prints the input, output and expected. But input and output is equal, because the duplicate_zeros affects the original list.

**Comment by juanan150** [comment]
I saw it too and fixed it in my PR.

Looking forward for you check! haha
